# Configuration for RuboCop (Ruby static code analyzer and formatter)
require:
  - rubocop-airbnb

AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 140

Style/SpecialGlobalVars:
  Enabled: false
