<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/oxid-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/oxid-ee/blob/master/LICENSE
 */

use Wirecard\Oxid\Model\Payment_Method;

class PaymentMethodTest extends OxidEsales\TestingLibrary\UnitTestCase
{

    private $_oPaymentMethosStub;

    protected function setUp()
    {
        $this->_oPaymentMethosStub = $this->getMockForAbstractClass(
            Payment_Method::class,
            [],
            '',
            false
        );
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetOxidPaymentMethodIdfromSdkString()
    {
        $sResult = Payment_Method::getOxidFromSDKName("paypal");
        $this->assertEquals('wdpaypal', $sResult);
    }

    public function testGetDefaultConfigFields()
    {


        $aResult = $this->_oPaymentMethosStub->getConfigFields();
        $this->assertArrayHasKey('apiUrl', $aResult);
        $this->assertArrayHasKey('httpUser', $aResult);
        $this->assertArrayHasKey('httpPassword', $aResult);
        $this->assertArrayHasKey('maid', $aResult);
        $this->assertArrayHasKey('secret', $aResult);
    }
}
